### ISSUE TITLE
When displaying a poll the user has already voted on

### ISSUE THREAD

**Issue by mrclay** [kevinjardine/shoutout#13]
Simply give a link to the poll, not the list of options.

**Comment by kevinjardine** [comment]
I'm not sure that I understand here - the plugin currently displays the poll results if a person has already voted. Are you asking that this not be displayed?

**Comment by mrclay** [comment]
Yes. Wherever the user voted, they've likely seen the results already. The goal is for polls to not take up a bunch of room in the stream. If they want to see latest results, they can click the link.

**Comment by mrclay** [comment]
Would be helpful to show # of responses when displaying:

`What's your favorite color? (5 responses)`

**Comment by kevinjardine** [comment]
Fixed.
