### ISSUE TITLE
After creating item, forwards to /activity despite setting

### ISSUE THREAD

**Issue by mrclay** [kevinjardine/shoutout#16]

**Comment by kevinjardine** [comment]
The setting determines the appearance of activity (title and whether the filter is preselected to shoutout). The shoutout page is always activity.

**Comment by mrclay** [comment]
I figured out a way to fix via our plugin.

**Comment by kevinjardine** [comment]
If you want to change or clarify the spec for this plugin, please do so. Much better than maintaining multiple repositories in my view.

**Comment by mrclay** [comment]
On our site, "Activity" has been replaced (rebranded) as Shout Out, so having URLs go to /shoutout is kind of a matter of identity as well as introducing less confusion. Not sure what the general user of this plugin will want, but I could imagine that being a good option.

**Comment by kevinjardine** [comment]
OK - I had thought that the requirement was that activity would become shoutout-enhanced. From my point of view, shoutout is really an enhancement to the activity river, not its own thing.

But if you would like some other behaviour, just shoot me an email describing it in more detail so I'm sure that I'll get it right.

**Comment by kevinjardine** [comment]
Also to add that a natural extension to shoutout would be to ajaxise the activity river so that it is periodically updated and so that comments and likes do not reload the whole page.
