### ISSUE TITLE
incorrect path to file attachment icon 

### ISSUE THREAD

**Issue by fullmetaljacket** [kevinjardine/shoutout#19]
After uploading an attachment to a shoutout, the path to the icon is:

mod/file/graphics/icons/application.gif

instead of:

/mod/file/graphics/icons/application.gif

**Comment by fullmetaljacket** [comment]
I think this only occurs when the file upload fails do to being greater than max size allowed.

**Comment by kevinjardine** [comment]
Looks like the problem was an incomplete icon link for binary data files, eg. spreadsheets. Can you confirm that this works for you now?

**Comment by fullmetaljacket** [comment]
works now, thanks!
