### ISSUE TITLE
Attachments save, both download as 0 byte files

### ISSUE THREAD

**Issue by mrclay** [kevinjardine/shoutout#2]

**Comment by kevinjardine** [comment]
Hmm. I can't reproduce this yet. If the attachment is too large or has the wrong extension, I get a popup JS error message (the correct behaviour), otherwise when I save the shoutout the attachments download as expected. What was the file mime type?

**Comment by mrclay** [comment]
in shoutout_download_attachment(), $full_file_path ends with `/Costa Rican Frog.jpg`, but on our disk that file was written as: `/Costa+Rican+Frog.jpg`.

**Comment by kevinjardine** [comment]
File names with spaces are asking for trouble. But I do realise that naive users might upload them (I never use them myself).

To protect ourselves, how about I replace spaces with underscores before saving the file?

**Comment by kevinjardine** [comment]
Not that I'm accusing you of being a naive user, of course - just a good tester!

;)

**Comment by mrclay** [comment]
urlencode() makes filenames that are safe on any platform: `urlencode('primer día.jpg') == 'primer+d%C3%ADa.jpg'`
You just have to remember to urldecode when sending back to the user

**Comment by kevinjardine** [comment]
I do urlencode, but will check on urldecode.

**Comment by kevinjardine** [comment]
Fixed on the live development site.
