### ISSUE TITLE
File attachments don't work in IE9

### ISSUE THREAD

**Issue by fullmetaljacket** [kevinjardine/shoutout#20]
There is a javascript error keeping IE9 from uploading a file to a shoutout.

**Comment by kevinjardine** [comment]
Do you have any text from the error?

**Comment by fullmetaljacket** [comment]
There are no errors, the progress bar spins while the file appears to upload, then it stops and a broken image icon appears.

**Comment by fullmetaljacket** [comment]
I believe the issue is in fileuploader.js:393. id is being set to "......iframe0" when it should just be set to a number.

**Comment by kevinjardine** [comment]
The problem was that the Ajax upload JS library I used was using a completely different approach (iframes)  for IE. It was forced to because IE is basically broken in the area of Ajaxy uploads (even IE9).

The library is fairly complex, so I missed that. My code now works with both approaches.
