### ISSUE TITLE
finfo_file(): File or path not found

### ISSUE THREAD

**Issue by fullmetaljacket** [kevinjardine/shoutout#21]
For every file we attach to a Shoutout, we get a corresponding entry in the Apache error logs:

PHP WARNING: 2012-02-16 20:24:55 (EST): "finfo_file(): File or path not found 'SantaHelpers.JPG'" in file /var/www/Elgg/mod/shoutout/models/model.php (line 512)

**Comment by kevinjardine** [comment]
Fixed. That function wants the full file path and in one case it was only getting the file name, not the full path.
