### ISSUE TITLE
file_get_contents: failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by fullmetaljacket** [kevinjardine/shoutout#22]
I'm not sure if it's every file, but there are many file_get_contents warnings when attaching a file to a shoutout:

PHP WARNING: 2012-02-16 16:13:17 (EST): "file_get_contents(/var/www/Elgg-data/2012/02/06/921/attachments//thumbBHPFC LOGOinvert.jpg): failed to open stream: No such file or directory" in file /var/www/Elgg/mod/shoutout/models/model.php (line 427

**Comment by kevinjardine** [comment]
These messages appear because an earlier bug meant that timestamps weren't being stored in attachment annotations for files with blanks in their names.

I fixed the bug but older shoutouts still trigger the error in listings.
