### ISSUE TITLE
Shoutout character length displays negative

### ISSUE THREAD

**Issue by naveensnayak** [kevinjardine/shoutout#23]
Hello Kevin, 
This is Naveen with the College of Education. Univ of Florida. 

Was doing some testing with the Shout-out plugin for Smartstart and  came across these things. 

Bug 1: When you "copy paste" a large text into the shout out area, the character limits read negative ( eg -98 characters left) 
Though mathematically correct, it would be good to display "You have exceeded the character limit, text will be truncated" 

Bug 2: After a copy paste of large text, i am able to submit the entire content ( > allowed character limit ) - and its posted to the server. No truncation is done. 
I think this behavior must be modified to give a user a message that the text will be truncated and the text must actually be truncated to the allowed limit 

Feature Req: When a long shout out wraps on the river page, users see a ( ... ) three dot and the message is truncated. Users of smartstart reported that they did not know how to see the full content. Unless you know that clicking on the "time-stamp" leads you to the full post, its difficult for a regular user 
Could you please add a "more" link for the truncated shout-outs -clicking which will have the same effect as clicking the time-stamp link in the shout-out heading

**Comment by kevinjardine** [comment]
These are actually three different issues. Dealing with them in turn:

_Bug 1_

When I tested this in Firefox, pasting was not changing the number. I added checks for the paste and input events and now the number of characters remaining goes down as expected in both Firefox and IE. 

The negative numbers are standard behaviour for countdown fields (see Twitter for example). I have made the behaviour even more Twitter like by making the negative numbers red and by disabling the post button for negative numbers. If you want non-Twitter like behaviour, please ask John or Steve to approve a feature enhancement for the next development phase and describe what the new behaviour should be in more detail.

_Bug 2_

Disabling the post button as described in 1 should avoid the truncation issue.

_Feature Request_

There is now a more link for shortened excerpts.
