### ISSUE TITLE
Comments on shoutouts show up as duplicate river items

### ISSUE THREAD

**Issue by mrclay** [kevinjardine/shoutout#3]

**Comment by kevinjardine** [comment]
I disabled the shoutout plugin and tried commenting on another river item and the comment appeared in the river (both under the item and as its own river item). So this appears to be a generic Elgg bug / unwelcome feature.

I could try filtering the activity river to remove shoutout comments (or perhaps even all comments?). What do you think?

**Comment by mrclay** [comment]
Isn't there a hook that's triggered when the comment is created? annotation/create or something like that? If so, could you cancel the action?

**Comment by mrclay** [comment]
I don't know what to do about comments in general. Ideally the river would consolidate similar items that are "close" to each other, but I know this is a terrifically difficult problem to solve.

**Comment by kevinjardine** [comment]
Comments need to be created because otherwise they would not appear at all but I will see if there is an easy way to stop JS type comments from being added it to the river. I would think that there would be.

**Comment by kevinjardine** [comment]
OK, this was straightforward. I overrode the comments add form when using it for the river and on individual shoutout views to add a no_river_comment flag. I also overrode the comments add action to not add a separate comment item if the no_river_comment flag is set.

The more general solution would be to _never_ add comments to the river but that might cause trouble with less lightweight content items. Eg. if someone posts a comment to a blog post a week after the post, no one would see it in the river unless they paginated way back in the river to find the original blog post.

I think the new behaviour makes sense for shoutouts as they should be more ephemeral - one would expect comments to appear within a few minutes of the shoutout so an extra river item is redundant.

**Comment by kevinjardine** [comment]
On your consolidation issue - I created a hot topics plugin for the University of Brighton that selected content items that were newer than n days and had more than m comments attached. m and n could be set by an admin. The hot topics plugin sorted content by the number of comments rather than time with the most commented items first. A hot topic automatically disappeared after n days to keep the listing fresh.

**Comment by kevinjardine** [comment]
I notice that the like and comment add and deletion actions in the river aren't ajaxy. They all reload the page (and do not even position the page to the correct river item). The comment deletion action leaves the river altogether and forwards to the individual item page.

If you had the time and budget, perhaps we should make the whole river a bit more ajaxy?

**Comment by kevinjardine** [comment]
Closing as the original issue is fixed.
