### ISSUE TITLE
Links are not auto-linked in the display

### ISSUE THREAD

**Issue by mrclay** [kevinjardine/shoutout#5]
This looks to be the best tool for this: https://github.com/jmrware/LinkifyURL/blob/master/linkify.js (or the PHP version)
The author seems to be a regex expert: http://jmrware.com/articles/2010/linkifyurl/linkify.html

**Comment by kevinjardine** [comment]
Fixed.

Fortunately Elgg has a builtin parse_urls() function to do this (used by the blog plugin for example).
