### ISSUE TITLE
Need to override shoutout comment email notifications

### ISSUE THREAD

**Issue by kevinjardine** [kevinjardine/shoutout#7]
Currently these are sent but assume that the object has a title and have an incorrect URL.

Eg.

You have a new comment on your item "" from Stephen Clay. It reads:

Comment left from shoutout page

**Comment by kevinjardine** [comment]
Before I do this, does it even make sense to have email notifications for shoutout comments?

**Comment by mrclay** [comment]
Just to follow-up, yes, please send an e-mail to the shoutout owner.

**Comment by kevinjardine** [comment]
I have looked into this further and comment notifications:

a. assume that all items have titles
b. are always sent
c. cannot be overridden

The only way I can fix this completely right now is over-ride the comment action itself and introduce special handling for certain kinds of entities.

A simpler hack for now would be to always give shoutouts the title "Shoutout".

The message sent would then be, for example:

You have a new comment on your item "Shoutout" from Stephen Clay. It reads: 

...

I understand that the notification system is going to be completely overhauled for Elgg 1.9 and hopefully this will introduce more flexibility.

**Comment by mrclay** [comment]
I think every email is sent through the (email, system) hook. They can be cancelled by returning false but I've just submitted a patch to alter them to: http://trac.elgg.org/ticket/4312

Would this help?

**Comment by kevinjardine** [comment]
My preference would be to just set shoutout titles for the time being. If you need more, then I think that over-riding the comment action would be preferable to either patching core Elgg on your server or over-riding the entire email system.

As I mentioned I think a new notifications system is really what we need here and that is already in the core Elgg timeline.

**Comment by mrclay** [comment]
OK, set the titles. I guess the first 200 chars and an ellipsis if that truncates?
We may revisit this later in the year.

**Comment by kevinjardine** [comment]
The notification email already includes the shoutout itself.

It's just that it needs a title as well, which I'm proposing be "Shoutout" for the time being.

**Comment by mrclay** [comment]
Yeah, that's fine.

**Comment by kevinjardine** [comment]
Done.
